name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        rustflags: ""
    - name: Build
      run: cargo build --verbose
    - name: Install tarpaulin
      run: cargo install --features vendored-openssl cargo-tarpaulin
    - name: Run tests with coverage
      run: cargo tarpaulin --all-features --workspace --out html
    - uses: actions/upload-artifact@v4
      with:
        name: test-coverage-report
        path: ./tarpaulin-report.html
